# Basic Information
title: Tommaso Di Francesco
position: Postdoctoral Researcher
affiliation: University of Bonn â€” Department of Economics (Finance Group)
email: t.difrancesco@uni-bonn.de

# Search Engine Optimization (SEO)
keywords: behavioral macro-finance, heterogeneous expectations, agent-based models, expectation formation, financial markets
description: Academic homepage of Tommaso Di Francesco, Postdoctoral Researcher in Finance at the University of Bonn. Research on behavioral macro-finance, heterogeneous beliefs, and agent-based models.
canonical: https://tommasodf.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=3JjzZZkAAAAJ&hl=it
cv_link: /assets/files/CV_template.pdf
github_link: https://github.com/TommasoDF
linkedin: https://www.linkedin.com/in/tommaso-di-francesco-03b967184/
#twitter: https://twitter.com/
orcid: https://orcid.org/0009-0003-3209-4320


# Images
avatar: /assets/img/fototessera_old.jpg
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif"

# Google Analytics
# Remove or comment out if unused
#google_analytics: UA-111540567-4

# Remote theme
remote_theme: yaoyao-liu/minimal-light

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/